### PR TITLE
Show OSD notification when default device changed

### PR DESCRIPTION
**Pull request by dameng324**
Like #50 issue said, it will show notification when default device changed. 

when I watch the notification, it's not clear to distinguish which device is the default now, because two notification is shown at the same time. so,I close previous notification when session changed.

It looks perfect now.

### CODE REVIEW

**Review by G-Stas — CHANGES_REQUESTED** [review]
Hello and thank you for the pull request! I'm okay with default device change notifications itself, but I don't like the idea of notifications replacing each other even if the device wasn't changed.
I would like the notifications to stack and close after timeout as before, but when default device change, all other notifications would close.

**Comment by dameng324** [comment]
Thanks for your reply. It will not replacing other notifications when the device wasn't changed.
Let me show the code:
https://github.com/dameng324/Volumey/blob/dc85d23fb08100a56133bb4a772cdf8ad60411be/Volumey/Helper/NotificationManagerHelper.cs#L41-L42
```csharp
if(_notificationManager.IsDisplayed(session.Id, resetDisplayTimer: true))
	return;
```
When the notification device is shown, It will reset the close delay and do nothing else. Only replace notification when device was changed.

**Comment by G-Stas** [comment]
This code closes all notifications before displaying the new notification, thus the new notification replaces all currently displayed notifications.
https://github.com/dameng324/Volumey/blob/dc85d23fb08100a56133bb4a772cdf8ad60411be/Volumey/Helper/NotificationManagerHelper.cs#L45-L48
```csharp
foreach(var key in _displayedNotificationKeys)
{
	_notificationManager.CloseNotification(key);
}
```

This behavior would be suitable if the code was invoked only by default device change, but it invokes on every new notification, whether it's the audio session volume change or default device change. That's what I'm talking about.

So as I said, I would like that all currently displayed notifications would be explicitly closed **_only_** when the default device changes, otherwise their display time shouldn't be controlled.

**Comment by dameng324** [comment]
Thanks for your explain and I see what you mean.
I record the last displayed id, and close all notification only when the last displayed session id has changed.
You can see what changed in the code.

**Comment by G-Stas** [comment]
Before your changes to the code, there are could be **_`several`_** notifications displayed at any given time, and they would stack on top of each other and would close only after their timeout expire. New notifications wouldn't close any of the currently displayed notification.

Your code closes _**`all`**_ currently displayed notifications before displaying the new notification, whether it's the audio session state change or default device change.

I want it to close currently displayed notifications **_`only`_** when the default device changes.

**Pull request closed without merging**
